language: php
sudo: false

php:
  - 5.6

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 6.
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "drush/drush:6.*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Download site.
  - drush make build-linedepping-dev.make ../linedepping_dev.dk
  - cd ../linedepping_dev.dk
  - chmod -R 777 sites/

before_script:

  - drush si linedepping_dk --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="linedepping.dk" --yes
  - drush cc all --yes

script: 
  - test -d profiles/linedepping_dk
  - test -d sites/all/modules/contrib
