language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make linedepping_dk.build ../linedepping_dev.dk
  - cd ../linedepping_dev.dk
  - sudo chmod -R 777 sites/
  - drush si linedepping_dk --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="linedepping.dk" --yes
  - drush cc all --yes

script: 
  - test -d profiles/linedepping_dk
